-- begin CUBATRAININGTASK_CAR_SERVICE_CENTER
alter table CUBATRAININGTASK_CAR_SERVICE_CENTER add constraint FK_CUBATRAININGTASK_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references CUBATRAININGTASK_CITY(ID)^
alter table CUBATRAININGTASK_CAR_SERVICE_CENTER add constraint FK_CUBATRAININGTASK_CAR_SERVICE_CENTER_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID)^
create index IDX_CUBATRAININGTASK_CAR_SERVICE_CENTER_CITY on CUBATRAININGTASK_CAR_SERVICE_CENTER (CITY_ID)^
create index IDX_CUBATRAININGTASK_CAR_SERVICE_CENTER_CREATOR on CUBATRAININGTASK_CAR_SERVICE_CENTER (CREATOR_ID)^
-- end CUBATRAININGTASK_CAR_SERVICE_CENTER
-- begin CUBATRAININGTASK_EMPLOYEE
alter table CUBATRAININGTASK_EMPLOYEE add constraint FK_CUBATRAININGTASK_EMPLOYEE_CENTER foreign key (CENTER_ID) references CUBATRAININGTASK_CAR_SERVICE_CENTER(ID)^
create index IDX_CUBATRAININGTASK_EMPLOYEE_CENTER on CUBATRAININGTASK_EMPLOYEE (CENTER_ID)^
-- end CUBATRAININGTASK_EMPLOYEE
-- begin CUBATRAININGTASK_REPAIR
alter table CUBATRAININGTASK_REPAIR add constraint FK_CUBATRAININGTASK_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references CUBATRAININGTASK_EMPLOYEE(ID)^
alter table CUBATRAININGTASK_REPAIR add constraint FK_CUBATRAININGTASK_REPAIR_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references CUBATRAININGTASK_CAR_SERVICE_CENTER(ID)^
create index IDX_CUBATRAININGTASK_REPAIR_EMPLOYEE on CUBATRAININGTASK_REPAIR (EMPLOYEE_ID)^
create index IDX_CUBATRAININGTASK_REPAIR_CAR_SERVICE_CENTER on CUBATRAININGTASK_REPAIR (CAR_SERVICE_CENTER_ID)^
-- end CUBATRAININGTASK_REPAIR

-- begin CUBATRAININGTASK_COMPANY
alter table CUBATRAININGTASK_COMPANY add constraint FK_CUBATRAININGTASK_COMPANY_ID foreign key (ID) references CUBATRAININGTASK_CUSTOMER(ID)^
-- end CUBATRAININGTASK_COMPANY
-- begin CUBATRAININGTASK_INDIVIDUAL
alter table CUBATRAININGTASK_INDIVIDUAL add constraint FK_CUBATRAININGTASK_INDIVIDUAL_ID foreign key (ID) references CUBATRAININGTASK_CUSTOMER(ID)^
-- end CUBATRAININGTASK_INDIVIDUAL
-- begin CUBATRAININGTASK_CUSTOMER
alter table CUBATRAININGTASK_CUSTOMER add constraint FK_CUBATRAININGTASK_CUSTOMER_CENTER foreign key (CENTER_ID) references CUBATRAININGTASK_CAR_SERVICE_CENTER(ID)^
create index IDX_CUBATRAININGTASK_CUSTOMER_CENTER on CUBATRAININGTASK_CUSTOMER (CENTER_ID)^
-- end CUBATRAININGTASK_CUSTOMER
