create table CUBATRAININGTASK_CITY (
    ID varchar(36) not null,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    NAME varchar(100) not null,
    CODE varchar(100) not null,
    --
    primary key (ID)
);

CREATE trigger CITY_EDITING_DEFAULT_FLAG_TRIGGER BEFORE UPDATE ON DEFAULT_CITY
FOR EACH ROW
UPDATE CUBATRAININGTASK_CITY C SET DEFAULT_FLAG = FALSE WHERE DEFAULT_FLAG = TRUE;


CREATE TRIGGER UPDATE_DEFAULT_FLAG_TRIGGER BEFORE UPDATE ON CUBATRAININGTASK_CITY-- alter table
FOR EACH ROW
IF(NEW.DEFAULT_FLAG=TRUE) THEN
    UPDATE CUBATRAININGTASK_CITY SET DEFAULT_FLAG = FALSE WHERE DEFAULT_FLAG = TRUE
    END IF;

CREATE TRIGGER UPDATE_DEFAULT_FLAG_TRIGGER BEFORE UPDATE ON CUBATRAININGTASK_CITY
FOR EACH ROW BEGIN IF (NEW.DEFAULT_CITY = TRUE) THEN
    UPDATE CUBATRAININGTASK_CITY SET DEFAULT_CITY = FALSE WHERE DEFAULT_CITY = TRUE

~~~
CREATE TRIGGER UPDATE_DEFAULT_FLAG_TRIGGER AFTER UPDATE ON CUBATRAININGTASK_CITY
FOR EACH ROW BEGIN ATOMIC IF (NEW.DEFAULT_CITY = TRUE) THEN
    UPDATE CUBATRAININGTASK_CITY SET DEFAULT_CITY = FALSE WHERE DEFAULT_CITY = TRUE
    END IF;
____
