alter table CUBATRAININGTASK_REPAIR add constraint FK_CUBATRAININGTASK_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references CUBATRAININGTASK_EMPLOYEE(ID);
create index IDX_CUBATRAININGTASK_REPAIR_EMPLOYEE on CUBATRAININGTASK_REPAIR (EMPLOYEE_ID);
