CREATE TRIGGER t1 AFTER UPDATE ON CUBATRAININGTASK_CITY
   REFERENCING NEW AS newrow FOR EACH ROW
      BEGIN ATOMIC
        IF (newrow.DEFAULT_CITY) = TRUE THEN
          UPDATE CUBATRAININGTASK_CITY set DEFAULT_CITY = FALSE WHERE ID <> newrow.id;
        END IF;
      END
      
      CREATE TRIGGER t2 AFTER INSERT ON CUBATRAININGTASK_CITY
   REFERENCING NEW AS newrow FOR EACH ROW
      BEGIN ATOMIC
        IF (newrow.DEFAULT_CITY) = TRUE THEN
          UPDATE CUBATRAININGTASK_CITY set DEFAULT_CITY = FALSE WHERE ID <> newrow.id;
        END IF;
      END
